package com.roadwatch.fl.model

data class SensorData(
    val timestamp: Long,
    val accX: Float = 0f,
    val accY: Float = 0f,
    val accZ: Float = 0f,
    val gyroX: Float = 0f,
    val gyroY: Float = 0f,
    val gyroZ: Float = 0f,
    val magX: Float = 0f,
    val magY: Float = 0f,
    val magZ: Float = 0f,
    val pressure: Float = 0f,
    val illuminance: Float = 0f,
    val dmAlpha: Float = 0f,
    val dmBeta: Float = 0f,
    val dmGamma: Float = 0f,
    val stepCount: Int = 0,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val speed: Float? = null,
    val altitude: Double? = null,
    val orientAzimuth: Float = 0f,
    val orientPitch: Float = 0f,
    val orientRoll: Float = 0f,
    val gravX: Float = 0f,
    val gravY: Float = 0f,
    val gravZ: Float = 0f,
    val rotX: Float = 0f,
    val rotY: Float = 0f,
    val rotZ: Float = 0f,
    val rotScalar: Float = 0f,
    var label: String = "normal",
    var motionState: String = "moving",
    var elapsedMs: Long = 0L
)
